### ISSUE TITLE
Compatibility with Autofac v6

### ISSUE THREAD

**Issue by alistairjevans** [autofac/Autofac.Extensions.Hosting#2]
v6 Compatibility and version dependency checks ahead of release.

**Comment by alistairjevans** [comment]
Doesn't look like this was ever released; does this repo need to be closed because it's been superseded by the generic host support in Autofac.Extensions.DependencyInjection?

**Comment by tillig** [comment]
The original intent was to make things more fluent, so instead of...

```c#
Host
  .CreateDefaultBuilder(args)
  .UseServiceProviderFactory(new AutofacServiceProviderFactory(b =>
    {
      b.RegisterType<T>();
    }));
```

...it could read just a tad nicer...

```c#
Host
  .CreateDefaultBuilder(args)
  .UseAutofac(b =>
    {
      b.RegisterType<T>();
    });
```

It wasn't included in Autofac.Extensions.DependencyInjection because we didn't want to tie that to the host builder; but, then, it's only three extension methods and doesn't add a whole lot. There wasn't clarity on whether we'd need more of these to help in complex situations.

I'm guessing not, though. And the cost/benefit of maintaining a package for three extension methods isn't great, so I don't know that we'd ever release it.

Yeah, we could probably, at a minimum, just close/lock/archive the repo. Might be worth keeping around for a bit just to see if .NET 5+ introduces complexity down the road?

**Comment by alistairjevans** [comment]
That's fine, we can leave it for now; I just won't bother updating it for v6.
